name    'puppetlabs-vswitch'
version '0.1.1'
source  'https://github.com/puppetlabs/puppetlabs-vswitch'
author  'Endre Karlson, Dan Bode, Ian Wells'
license 'Apache License 2.0'
summary 'Puppet module for OpenVSwitch and other vSwitches'
description 'Puppet module to install and configure the OpenVSwitch and other vSwitches'
project_page 'https://launchpad.net/puppet-openstack'
